# Generated by Django 2.2 on 2019-05-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_person', models.CharField(max_length=200)),
                ('third_person', models.CharField(max_length=200)),
            ],
        ),
    ]
